### ISSUE TITLE
Building from sources problem

### ISSUE THREAD

**Issue by awelc** [uber/prototool#505]
I am trying to build from sources on macOS Mojave 10.14.6 with bazel 0.28.1 and I am getting the following error (tried both `bazel build //...` and `bazel build //cmd/prototool/...`):

```
ERROR: /private/var/tmp/_bazel_XXXXXX/397e3415fefc6740f513a0807c276143/external/io_bazel_rules_go/BUILD.bazel:62:1: in go_context_data rule @io_bazel_rules_go//:go_context_data: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_XXXXXX/397e3415fefc6740f513a0807c276143/external/io_bazel_rules_go/BUILD.bazel", line 62
		go_context_data(name = 'go_context_data')
	File "/private/var/tmp/_bazel_XXXXXX/397e3415fefc6740f513a0807c276143/external/io_bazel_rules_go/go/private/context.bzl", line 396, in _go_context_data_impl
		cc_common.configure_features(cc_toolchain = cc_toolchain, reque..., ...)
Incompatible flag --incompatible_require_ctx_in_configure_features has been flipped, and the mandatory parameter 'ctx' of cc_common.configure_features is missing. Please add 'ctx' as a named parameter. See https://github.com/bazelbuild/bazel/issues/7793 for details.
ERROR: Analysis of target '//cmd/prototool:prototool' failed; build aborted: Analysis of target '@io_bazel_rules_go//:go_context_data' failed; build aborted
I
```

I looked at both the bazel [issue](https://github.com/bazelbuild/bazel/issues/7793) referenced in the bug report and also tried to search for a solution but without much success... 

The reason I need to build from sources is that I am trying to test some local changes, but the build fails with no modifications of any kind.

**Comment by smaye81** [comment]
Did you try `make bazelbuild`?

**Comment by smaye81** [comment]
Closing this.  If this is still an issue, please reopen.
